// <auto-generated />
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230114075931_CreateMonsters")]
    partial class CreateMonsters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("int");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("int");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("int");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArmorClass = 12,
                            AttackModifier = 18,
                            AttackPerRound = 1,
                            Damage = "9d8",
                            DamageModifier = 3,
                            HitPoints = 58,
                            Name = "Mimic"
                        },
                        new
                        {
                            Id = 2,
                            ArmorClass = 19,
                            AttackModifier = 144,
                            AttackPerRound = 1,
                            Damage = "24d12",
                            DamageModifier = 7,
                            HitPoints = 300,
                            Name = "Arasta"
                        },
                        new
                        {
                            Id = 3,
                            ArmorClass = 17,
                            AttackModifier = 20,
                            AttackPerRound = 1,
                            Damage = "10d8",
                            DamageModifier = 3,
                            HitPoints = 65,
                            Name = "Bugbear Chief"
                        },
                        new
                        {
                            Id = 4,
                            ArmorClass = 11,
                            AttackModifier = 0,
                            AttackPerRound = 1,
                            Damage = "10d8",
                            DamageModifier = -2,
                            HitPoints = 45,
                            Name = "Agony"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
